### PR TITLE
Allow custom resolver

### PR DESCRIPTION
**Pull request by joesis**
It's part of https://github.com/getlantern/lantern/issues/4182, though it doesn't seem necessary now

### CODE REVIEW

**Comment by oxtoacart** [comment]
@joesis Since it's not necessary, should we close?

**Comment by joesis** [comment]
The flashlight PR code uses the new `NewFromReader()` signature. Maybe wait until that PR is finalized.

**Comment by oxtoacart** [comment]
Cool.

**Comment by joesis** [comment]
We don't really need this

**Pull request closed without merging**
